from app.core.database import db, initialize_database
from peewee import Model, CharField
from .base import insert_enum_values
from unidecode import unidecode

class Hobby(Model):
    id = CharField(unique=True, index=True, primary_key=True, null=True)

    class Meta:
        database = db


initialize_database([Hobby])

_values = [
    "Antiquing",
    "Aquarium Keeping",
    "Archery",
    "Astrology",
    "Astronomy",
    "Baking",
    "Beekeeping",
    "Biking",
    "Billiards",
    "Birding",
    "Blogging",
    "Board Gaming",
    "Bodybuilding",
    "Bowling",
    "Brewing Beer",
    "Cake Decorating",
    "Calligraphy",
    "Camping",
    "Candle Making",
    "Canyoneering",
    "Card Games",
    "Chess Playing",
    "Collecting",
    "Coloring",
    "Cooking",
    "Cross-stitching",
    "Crossword Puzzles",
    "Dancing",
    "Dining Out",
    "Drawing",
    "Entertaining",
    "Fishing",
    "Flower Arranging",
    "Flower Pressing",
    "Gardening",
    "Genealogy",
    "Glass Blowing",
    "Go Kart Racing",
    "Golfing",
    "Graffiti Art",
    "Hiking",
    "Home Improvement",
    "Horseback Riding",
    "Hula Hooping",
    "Ice Skating",
    "Interior Decorating",
    "Jewelry Making",
    "Jigsaw Puzzling",
    "Juggling",
    "Kayaking",
    "Knitting",
    "Latte Art",
    "Learning a New Language",
    "Leather Crafting",
    "Macramé",
    "Magic",
    "Making Model Planes/Cars",
    "Martial Arts",
    "Meditation",
    "Metal Detecting",
    "Mixology",
    "Mountaineering",
    "Musical Instrument",
    "Origami",
    "Paintball",
    "Painting",
    "Papermaking",
    "Photography",
    "Pickling & Canning",
    "Playing the Stock Market",
    "Pottery",
    "Rappelling",
    "Rapping",
    "Reading",
    "Restoring Furniture",
    "Rock Climbing",
    "Running",
    "Sailing",
    "Scrapbooking",
    "Scuba Diving",
    "Sewing",
    "Singing",
    "Skateboarding",
    "Snowboarding/Skiing",
    "Soap Making",
    "Spelunking",
    "Stand Up Comedy & Improv",
    "Stand Up Paddle Boarding",
    "Surfing",
    "Swimming",
    "Tennis",
    "Traveling",
    "Video Gaming",
    "Volunteering",
    "Watching Sports",
    "Watching TV Series & Movies",
    "White Water Rafting",
    "Wine Tasting",
    "Woodworking",
    "Writing",
    "Yoga",
]

_values = [unidecode(v) for v in _values]
insert_enum_values(Hobby, _values)
