from app.core.database import db, initialize_database
from peewee import Model, CharField
from .base import insert_enum_values

class Profession(Model):
    id = CharField(unique=True, index=True, primary_key=True, null=True)

    class Meta:
        database = db


initialize_database([Profession])



_values = [
    "Actor",
    "Artist",
    "Dancer",
    "Dance Teacher",
    "Model",
    "Musician",
    "Stage Manager",
    "Theater Stage Director",
    "Art Director",
    "Arts Administrator",
    "Audio Engineer",
    "Creative Director",
    "Event Coordinator",
    "Event Planner",
    "Music Producer",
    "Producer",
    "Production Assistant",
    "3D Artist",
    "DJ",
    "Film Producer",
    "Game Designer",
    "Graphic Designer",
    "Photographer",
    "Video Editor",
    "Videographer",
    "Copywriter",
    "Freelance Writer",
    "Grant Writer",
    "Interpreter",
    "Journalist",
    "Public Relations Strategist",
    "Technical Writer",
    "Transcriptionist",
    "Translator",
    "Account Manager",
    "Accounting Assistant",
    "Accountant",
    "Accounts Payable Specialist",
    "Accounts Receivable Manager",
    "Billing Specialist",
    "Certified Public Accountant (CPA)",
    "Debt Collector",
    "Payroll Specialist",
    "Staff Accountant",
    "Tax Intern",
    "Tax Preparer",
    "Bookkeeper",
    "Entry Level Financial Analyst",
    "Finance Director",
    "Financial Advisor",
    "Financial Analyst",
    "Bank Teller",
    "Branch Manager",
    "Claims Adjuster",
    "Credit Analyst",
    "Insurance Agent",
    "Investment Banking",
    "Loan Processor",
    "Mortgage Loan Officer",
    "Personal Banker",
    "Human Resources Associate",
    "HR Business Partner",
    "HR Coordinator",
    "HR Generalist",
    "Recruiter",
    "Administrative Assistant",
    "Clerk",
    "Executive Assistant",
    "Front Desk Agent",
    "Healthcare Coordinator",
    "Medical Assistant",
    "Medical Billing and Coding Manager",
    "Medical Office Manager",
    "Office Administrator",
    "Office Assistant",
    "Office Manager",
    "Personal Assistant",
    "Program Coordinator",
    "Receptionist",
    "Secretary",
    "Virtual Assistant",
    "Account Executive",
    "Big Data Analyst",
    "Business Administrator",
    "Business Analyst",
    "Business Consultant",
    "Business Development Manager",
    "Business Intelligence Analyst",
    "Consultant",
    "Data Analyst",
    "Data Entry Clerk",
    "Data Scientist",
    "Database Developer",
    "Project Coordinator",
    "Scrum Master",
    "Assistant Manager",
    "Associate Product Manager",
    "Business Manager",
    "Business Owner",
    "CEO (Chief Executive Officer)",
    "CFO (Chief Financial Officer)",
    "Change Manager",
    "CIO (Chief Information Officer)",
    "Contract Specialist",
    "COO (Chief Operating Officer)",
    "CTO (Chief Technology Officer)",
    "Director Of Product Management",
    "Executive Director",
    "General Manager",
    "Hotel General Manager",
    "Independent Contractor",
    "Management Consulting",
    "Operations Manager",
    "Product Manager",
    "Product Manager Intern",
    "Program Manager",
    "Project Manager",
    "Senior Product Manager",
    "Software Product Manager",
    "Supervisor",
    "Technical Product Manager",
    "Vice President",
    "Child Care Provider",
    "Daycare Worker",
    "Nanny",
    "Assistant Principal",
    "Camp Counselor",
    "Senior Coach",
    "Instructional Designer",
    "Librarian",
    "Library Page",
    "Life Coach",
    "Mentor",
    "Paraprofessional",
    "Pastor",
    "Principal",
    "Registered Behavior Technician (RBT)",
    "School Counselor",
    "Superintendent Of Schools",
    "Adjunct Professor",
    "Art Teacher",
    "College Professor",
    "Elementary Teacher",
    "ESL Teacher",
    "Math Teacher",
    "Math Tutor",
    "Preschool Teacher",
    "Special Education Teacher",
    "Substitute Teacher",
    "Teacher Assistant",
    "Teacher",
    "Tutor",
    "ABA Therapist",
    "Caregiver",
    "Home Health Aide",
    "Hospital Housekeeping",
    "Hospital Volunteer",
    "Mental Health Counselor",
    "Patient Care Technician (PCT)",
    "Psychiatrist",
    "Speech-Language Pathologist",
    "Ultrasound Tech",
    "Veterinary Assistant",
    "Veterinary Technician",
    "Case Manager",
    "Medical Assistant",
    "Medical Receptionist",
    "Medical Scribe",
    "Medical Technologist",
    "Optometrist",
    "Patient Access Representative",
    "Pharmacist",
    "Pharmacy Intern",
    "Pharmacy Technician",
    "Phlebotomist",
    "Retail Pharmacist",
    "Surgical Tech",
    "Volunteer Medical Assistant",
    "Certified Nursing Assistant (CNA)",
    "Charge Nurse",
    "Hospice Nurse",
    "ICU Registered Nurse",
    "Labor And Delivery Nurse",
    "Licensed Practical Nurse (LPN)",
    "NICU Nurse",
    "Nurse Practitioner",
    "Nursing Student",
    "Oncology Nurse",
    "Operating Room Nurse",
    "Orthopedic Nurse",
    "Pediatric Nurse",
    "Preceptorship Nurse",
    "Registered Nurse (RN)",
    "School Nurse",
    "Telemetry Nurse",
    "Travel Nurse",
    "Dental Assistant",
    "Dental Hygienist",
    "Dental Office Manager",
    "Dentist",
    "Dispensing Optician",
    "OB/GYN Medical Assistant",
    "Optician",
    "Interior Designer",
    "Leasing Agent",
    "Property Manager",
    "Real Estate Agent",
    "Custodian",
    "Diesel Mechanic",
    "Electrician",
    "Handyman",
    "HVAC Technician",
    "Janitor",
    "Maintenance Supervisor",
    "Maintenance Worker",
    "Mechanic",
    "Pipefitter",
    "Plumber",
    "Welder",
    "Architect",
    "Assembler",
    "Carpenter",
    "Construction Project Manager",
    "Construction Worker",
    "Forklift Operator",
    "General Contractor",
    "Laborer",
    "Machine Operator",
    "Project Engineer",
    "Superintendent",
    "Chemical Engineer",
    "Civil Engineer",
    "Electrical Engineer",
    "Industrial Engineer",
    "Manufacturing Engineer",
    "Mechanical Engineer",
    "Network Engineer",
    "Process Engineer",
    "Quality Assurance",
    "Quality Engineer",
    "SDET (Software Development Engineer in Test)",
    "Chiropractor",
    "Dietary Aide",
    "Dietitian",
    "Health Coach",
    "Occupational Therapy Assistant",
    "Personal Trainer",
    "Physical Therapy Aide",
    "Physical Therapist",
    "Physician Assistant",
    "Respiratory Therapist",
    "Yoga Teacher",
    "Cosmetologist",
    "Esthetician",
    "Hair Stylist",
    "Makeup Artist",
    "Massage Therapist",
    "Law Clerk",
    "Lawyer",
    "Legal Assistant",
    "Paralegal",
    "Politician",
    "Military Officer",
    "Correctional Officer",
    "EMT",
    "Firefighter",
    "Lifeguard",
    "Loss Prevention Specialist",
    "Paramedic",
    "Police Officer",
    "Public Health",
    "Security Guard",
    "Security Officer",
    "Call Center Representative",
    "Customer Service Representative",
    "Customer Service Supervisor",
    "Customer Success Manager",
    "Brand Ambassador",
    "Communications Specialist",
    "Community Manager",
    "Digital Marketing Manager",
    "Marketing Assistant",
    "Marketing Coordinator",
    "Marketing Intern",
    "Marketing Manager",
    "Product Marketing Manager",
    "SEO",
    "Social Media Assistant",
    "Social Media Manager",
    "Social Media Marketing",
    "Car Salesman",
    "Ecommerce Specialist",
    "Fundraising Representative",
    "Sales Associate",
    "Sales Engineer",
    "Sales Manager",
    "Bioinformatician",
    "Chemist",
    "Computer Science",
    "Computer Science Intern",
    "Lab Assistant",
    "Lab Technician",
    "Baker",
    "Banquet Server",
    "Barback",
    "Barista",
    "Bartender",
    "Budtender",
    "Busser",
    "Chef",
    "Dishwasher",
    "Hostess",
    "Line Cook",
    "Prep Cook",
    "Restaurant Manager",
    "Server",
    "Waiter/Waitress",
    "Concierge",
    "Flight Attendant",
    "Front Desk Clerk",
    "Housekeeper",
    "Night Auditor",
    "Travel Agent",
    "Cashier",
    "Grocery Store Cashier",
    "Retail Manager",
    "Retail Sales Associate",
    "Store Manager",
    "Accounting Intern",
    "Recent Graduate",
    "Resident Assistant",
    "Graduate Assistant",
    "MBA",
    "PhD",
    "Designer",
    "UX Designer",
    "Web Designer",
    "Computer Technician",
    "Cyber Security Engineer",
    "Data Engineer",
    "Database Administrator",
    "Desktop Support Technician",
    "Help Desk Specialist",
    "IT Director",
    "IT Project Manager",
    "IT Support Specialist",
    "Network Administrator",
    "QA Tester",
    "System Administrator",
    "Technical Support Engineer",
    ".NET Developer",
    "AWS Developer",
    "Azure Developer",
    "DevOps Engineer",
    "Front-End Developer",
    "Full Stack Developer",
    "Java Developer",
    "Power BI Developer",
    "Programmer",
    "Python Developer",
    "Salesforce Developer",
    "Software Engineer",
    "SQL Developer",
    "Tableau Developer",
    "UI Developer",
    "Web Developer",
    "Bus Driver",
    "Delivery Driver",
    "Pilot",
    "Truck Driver",
    "Uber Driver",
    "Logistics Coordinator",
    "Logistics Manager",
    "Supply Chain Analyst",
    "Supply Chain Manager",
    "Supply Chain Specialist",
    "Inventory Manager",
    "Inventory Specialist",
    "Warehouse Manager",
    "Warehouse Worker",
]
_values = list(set(_values))
insert_enum_values(Profession, _values)
